"""m

Revision ID: 0b87d9299ea6
Revises: 1ef08f17ab42
Create Date: 2025-02-03 13:07:06.753698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b87d9299ea6'
down_revision: Union[str, None] = '1ef08f17ab42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
