"""m

Revision ID: 729b4aea311b
Revises: 4d8a98231051
Create Date: 2025-02-18 17:07:17.306016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729b4aea311b'
down_revision: Union[str, None] = '4d8a98231051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.drop_column('purity')

    # ### end Alembic commands ###
